services:
  postgres:
    image:  postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: spring-app-db
      POSTGRES_USER: spring-app
      POSTGRES_PASSWORD: spring-app*)
      POSTGRES_ROOT_PASSWORD: root*)
    ports:
      - "5432:5432"
